name = "GridVAMP"
uuid = "e2a18fb8-4a0f-4b9e-a519-a2cfeccb4106"
authors = ["Gustavo Goretkin <gustavo.goretkin@gmail.com>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
EponymKeywordSyntax = "d38a42db-3801-4ba0-8d69-b527598ec48c"
EponymTuples = "97e2ac4a-e175-5f49-beb1-4d6866a6cdc3"

[compat]
julia = "^1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
